#!/bin/bash
#
# aliases, by default.

# enable colors for ls and dir
alias ls='ls --color=auto'
alias dir='dir --color=auto'

# *ubuntu shortcuts
alias agi='sudo apt-get install'
alias acs='sudo apt-cache search'
alias agr='sudo apt-get remove'

# emacsclient!
alias ec='emacsclient -n'
