#!/bin/sh
#
# aliases, by default.

# enable colors for ls and dir
alias dir='dir --color=auto'

# *ubuntu shortcuts
alias agi='sudo apt-get install'
alias acs='sudo apt-cache search'
alias agr='sudo apt-get remove'

# git aliases
alias gst='git status'
alias gp='git push'
alias gd='git diff'
alias gdc='git diff --cached'
alias gcm='git commit -m'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias grst='git reset --hard HEAD'
alias gf='git fetch'
alias gk='gitk --all'
alias t='git status'
alias a='git add'

# some other aliases
alias screen='screen -h 5000'

# rails stuff
alias r='be rake'
alias be='bundle exec'
alias bec='bundle exec cucumber'
alias br='bundle exec rails'
alias rs='bundle exec rails server'

# Mac-OS related stuff
if [[ "$UNAME_S" == "Darwin" ]]; then
   alias ls='ls -G'
   alias emacs='open -a Emacs.app'
   alias ec='/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n'
else
   alias ls='ls --color=always'
   alias ec='emacsclient -n'
fi
