#!/bin/sh
#
# aliases, by default.

# enable colors for ls and dir
alias ls='ls --color=always'
alias dir='dir --color=auto'

# *ubuntu shortcuts
alias agi='sudo apt-get install'
alias acs='sudo apt-cache search'
alias agr='sudo apt-get remove'

# emacsclient!
alias ec='emacsclient -n'

# git aliases
alias gst='git status'
alias gp='git push'
alias gd='git diff'
alias gdc='git diff --cached'
alias gcm='git commit -m'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias grst='git reset --hard HEAD'
alias gf='git fetch'
alias gk='gitk --all'

# some other aliases
alias psr='ps axu | grep ruby'
alias screen='screen -h 5000'

# rails stuff
alias r='rake'
alias be='bundle exec'
alias bec='bundle exec cucumber'
alias br='bundle exec rails'
alias rs='bundle exec rails server'
